$schema: http://azureml/sdk-2-0/Schedule.json
name: taxidata_model_monitoring
display_name: Taxi Regression model monitoring
description: Taxi Regression model monitoring with advanced configurations

trigger:
  # perform model monitoring activity daily at 3:15am
  type: recurrence
  frequency: day #can be minute, hour, day, week, month
  interval: 1 # #every day
  schedule: 
    hours: 3 # at 3am
    minutes: 15 # at 15 mins after 3am

create_monitor:
  compute: 
    instance_type: standard_e4s_v3
    runtime_version: 3.3
  monitoring_target:
    ml_task: Regression
    endpoint_deployment_id: azureml:mlw-srramv2-0001dev-ypxli:taxi-model-1
  monitoring_signals:
    advanced_data_drift: # monitoring signal name, any user defined name works
      type: data_drift
      # target_dataset is optional. By default target dataset is the production inference data associated with Azure Machine Learning online endpoint
      reference_data:
        input_data:
          path: azureml:taxidata:2.0 # use training data as comparison baseline
          type: mltable
        data_context: training
        target_column_name: cost
      features: 
        top_n_feature_importance: 10 # monitor drift for top 20 features
      metric_thresholds:
        numerical:
          jensen_shannon_distance: 0.01
        categorical:
          pearsons_chi_squared_test: 0.02
    advanced_data_quality:
      type: data_quality
      # target_dataset is optional. By default target dataset is the production inference data associated with Azure Machine Learning online depoint
      reference_data:
        input_data:
          path: azureml:taxidata:2.0
          type: mltable
        data_context: training
      features: # monitor data quality for 3 individual features only
        - distance
        - passengers
        - pickup_weekday
      metric_thresholds:
        numerical:
          null_value_rate: 0.05
        categorical:
          out_of_bounds_rate: 0.03

    feature_attribution_drift_signal:
      type: feature_attribution_drift
      # production_data: is not required input here
      # Please ensure Azure Machine Learning online endpoint is enabled to collected both model_inputs and model_outputs data
      # Azure Machine Learning model monitoring will automatically join both model_inputs and model_outputs data and used it for computation
      reference_data:
        input_data:
          path: azureml:taxidata:2.0
          type: mltable
        data_context: training
        target_column_name: cost
      metric_thresholds:
        normalized_discounted_cumulative_gain: 0.9
  
  alert_notification:
    emails:
      - srram@microsoft.com